
%%


% This script is located in: 
cd /Users/srishtidasarathy/Documents/'Documents - Srishti’s MacBook Pro '/Bowman/SouthernOcean_Causal_Analysis/Code

% All years of analysis are saved in:
cd /Volumes/'G-DRIVE mobile USB'/NEW_AOD/AOD_matfiles


%% Combining all MODIS mat files for all years in bellingshausen sea into one

load('Master_MODIS_files_2018.mat')
load('Master_MODIS_files_2017.mat')
load('Master_MODIS_files_2016.mat')
load('Master_MODIS_files_2015.mat')
load('Master_MODIS_files_2014.mat')
load('Master_MODIS_files_2013.mat')
load('Master_MODIS_files_2012.mat')
load('Master_MODIS_files_2011.mat')
load('Master_MODIS_files_2010.mat')
load('Master_MODIS_files_2009.mat')
load('Master_MODIS_files_2008.mat')
load('Master_MODIS_files_2007.mat')


%%

cd /Users/srishtidasarathy/Documents/'Documents - Srishti’s MacBook Pro '/Bowman/SouthernOcean_Causal_Analysis/Variables/AOD_matfiles/
%%
Master_time_2007_2018 = cat(1, ...
    Master_time_2007, ...
    Master_time_2008,...
    Master_time_2009,...
    Master_time_2010,...
    Master_time_2011,...
    Master_time_2012,...
    Master_time_2013,...
    Master_time_2014,...
    Master_time_2015,...
    Master_time_2016,...
    Master_time_2017,...
    Master_time_2018);


datetime_2007_2018 = datetime(str2num(Master_time_2007_2018(:, 1:4)), 1, str2num(Master_time_2007_2018(:, 5:7))); 

save('datetime_2007_2018.mat', 'datetime_2007_2018', '-v7.3');

Master_AOD_total_2007_2018 = cat(3, ...
    Master_AOD_total_2007, ...
    Master_AOD_total_2008,...
    Master_AOD_total_2009,...
    Master_AOD_total_2010,...
    Master_AOD_total_2011,...
    Master_AOD_total_2012,...
    Master_AOD_total_2013,...
    Master_AOD_total_2014,...
    Master_AOD_total_2015,...
    Master_AOD_total_2016,...
    Master_AOD_total_2017,...
    Master_AOD_total_2018);

save('Master_AOD_total_2007_2018.mat', 'Master_AOD_total_2007_2018', '-v7.3');

Master_AOD_total_std_2007_2018 = cat(3, ...
    Master_AOD_total_std_2007, ...
    Master_AOD_total_std_2008,...
    Master_AOD_total_std_2009,...
    Master_AOD_total_std_2010,...
    Master_AOD_total_std_2011,...
    Master_AOD_total_std_2012,...
    Master_AOD_total_std_2013,...
    Master_AOD_total_std_2014,...
    Master_AOD_total_std_2015,...
    Master_AOD_total_std_2016,...
    Master_AOD_total_std_2017,...
    Master_AOD_total_std_2018);

save('Master_AOD_total_std_2007_2018.mat', 'Master_AOD_total_std_2007_2018', '-v7.3');

Master_AOD_total_min_2007_2018 = cat(3, ...
    Master_AOD_total_min_2007, ...
    Master_AOD_total_min_2008,...
    Master_AOD_total_min_2009,...
    Master_AOD_total_min_2010,...
    Master_AOD_total_min_2011,...
    Master_AOD_total_min_2012,...
    Master_AOD_total_min_2013,...
    Master_AOD_total_min_2014,...
    Master_AOD_total_min_2015,...
    Master_AOD_total_min_2016,...
    Master_AOD_total_min_2017,...
    Master_AOD_total_min_2018);

save('Master_AOD_total_min_2007_2018.mat', 'Master_AOD_total_min_2007_2018', '-v7.3');

Master_AOD_total_max_2007_2018 = cat(3, ...
    Master_AOD_total_max_2007, ...
    Master_AOD_total_max_2008,...
    Master_AOD_total_max_2009,...
    Master_AOD_total_max_2010,...
    Master_AOD_total_max_2011,...
    Master_AOD_total_max_2012,...
    Master_AOD_total_max_2013,...
    Master_AOD_total_max_2014,...
    Master_AOD_total_max_2015,...
    Master_AOD_total_max_2016,...
    Master_AOD_total_max_2017,...
    Master_AOD_total_max_2018);

save('Master_AOD_total_max_2007_2018.mat', 'Master_AOD_total_max_2007_2018', '-v7.3');

Master_AOD_fine_2007_2018 = cat(3, ...
    Master_AOD_fine_2007, ...
    Master_AOD_fine_2008,...
    Master_AOD_fine_2009,...
    Master_AOD_fine_2010,...
    Master_AOD_fine_2011,...
    Master_AOD_fine_2012,...
    Master_AOD_fine_2013,...
    Master_AOD_fine_2014,...
    Master_AOD_fine_2015,...
    Master_AOD_fine_2016,...
    Master_AOD_fine_2017,...
    Master_AOD_fine_2018);

save('Master_AOD_fine_2007_2018.mat', 'Master_AOD_fine_2007_2018', '-v7.3');

Master_AOD_coarse_2007_2018 = cat(3, ...
    Master_AOD_coarse_2007, ...
    Master_AOD_coarse_2008,...
    Master_AOD_coarse_2009,...
    Master_AOD_coarse_2010,...
    Master_AOD_coarse_2011,...
    Master_AOD_coarse_2012,...
    Master_AOD_coarse_2013,...
    Master_AOD_coarse_2014,...
    Master_AOD_coarse_2015,...
    Master_AOD_coarse_2016,...
    Master_AOD_coarse_2017,...
    Master_AOD_coarse_2018);

save('Master_AOD_coarse_2007_2018.mat', 'Master_AOD_coarse_2007_2018', '-v7.3')

Master_AOD_total_pixelcounts_2007_2018 = cat(3, ...
    Master_AOD_total_pixelcounts_2007, ...
    Master_AOD_total_pixelcounts_2008,...
    Master_AOD_total_pixelcounts_2009,...
    Master_AOD_total_pixelcounts_2010,...
    Master_AOD_total_pixelcounts_2011,...
    Master_AOD_total_pixelcounts_2012,...
    Master_AOD_total_pixelcounts_2013,...
    Master_AOD_total_pixelcounts_2014,...
    Master_AOD_total_pixelcounts_2015,...
    Master_AOD_total_pixelcounts_2016,...
    Master_AOD_total_pixelcounts_2017,...
    Master_AOD_total_pixelcounts_2018);

save('Master_AOD_total_pixelcounts_2007_2018.mat','Master_AOD_total_pixelcounts_2007_2018', '-v7.3');


Master_Ff_small_mean_2007_2018 = cat(3, ...
    Master_Ff_small_mean_2007, ...
    Master_Ff_small_mean_2008,...
    Master_Ff_small_mean_2009,...
    Master_Ff_small_mean_2010,...
    Master_Ff_small_mean_2011,...
    Master_Ff_small_mean_2012,...
    Master_Ff_small_mean_2013,...
    Master_Ff_small_mean_2014,...
    Master_Ff_small_mean_2015,...
    Master_Ff_small_mean_2016,...
    Master_Ff_small_mean_2017,...
    Master_Ff_small_mean_2018);

save('Master_Ff_small_mean_2007_2018.mat', 'Master_Ff_small_mean_2007_2018', '-v7.3');

Master_Ff_small_std_2007_2018 = cat(3, ...
    Master_Ff_small_std_2007, ...
    Master_Ff_small_std_2008,...
    Master_Ff_small_std_2009,...
    Master_Ff_small_std_2010,...
    Master_Ff_small_std_2011,...
    Master_Ff_small_std_2012,...
    Master_Ff_small_std_2013,...
    Master_Ff_small_std_2014,...
    Master_Ff_small_std_2015,...
    Master_Ff_small_std_2016,...
    Master_Ff_small_std_2017,...
    Master_Ff_small_std_2018);

save('Master_Ff_small_std_2007_2018.mat', 'Master_Ff_small_std_2007_2018', '-v7.3');

Master_Ff_small_min_2007_2018 = cat(3, ...
    Master_Ff_small_min_2007, ...
    Master_Ff_small_min_2008,...
    Master_Ff_small_min_2009,...
    Master_Ff_small_min_2010,...
    Master_Ff_small_min_2011,...
    Master_Ff_small_min_2012,...
    Master_Ff_small_min_2013,...
    Master_Ff_small_min_2014,...
    Master_Ff_small_min_2015,...
    Master_Ff_small_min_2016,...
    Master_Ff_small_min_2017,...
    Master_Ff_small_min_2018);

save('Master_Ff_small_min_2007_2018.mat', 'Master_Ff_small_min_2007_2018', '-v7.3');

Master_Ff_small_max_2007_2018 = cat(3, ...
    Master_Ff_small_max_2007, ...
    Master_Ff_small_max_2008,...
    Master_Ff_small_max_2009,...
    Master_Ff_small_max_2010,...
    Master_Ff_small_max_2011,...
    Master_Ff_small_max_2012,...
    Master_Ff_small_max_2013,...
    Master_Ff_small_max_2014,...
    Master_Ff_small_max_2015,...
    Master_Ff_small_max_2016,...
    Master_Ff_small_max_2017,...
    Master_Ff_small_max_2018);

save('Master_Ff_small_max_2007_2018.mat', 'Master_Ff_small_max_2007_2018', '-v7.3');

Master_Ff_small_QA_mean_2007_2018 = cat(3, ...
    Master_Ff_small_QA_mean_2007, ...
    Master_Ff_small_QA_mean_2008,...
    Master_Ff_small_QA_mean_2009,...
    Master_Ff_small_QA_mean_2010,...
    Master_Ff_small_QA_mean_2011,...
    Master_Ff_small_QA_mean_2012,...
    Master_Ff_small_QA_mean_2013,...
    Master_Ff_small_QA_mean_2014,...
    Master_Ff_small_QA_mean_2015,...
    Master_Ff_small_QA_mean_2016,...
    Master_Ff_small_QA_mean_2017,...
    Master_Ff_small_QA_mean_2018);

save('Master_Ff_small_QA_mean_2007_2018.mat', 'Master_Ff_small_QA_mean_2007_2018', '-v7.3');




%%
% Spatial subsetting of Regions A (Corner), B (Central), & C (Southernmost) of the Bellingshausen Sea. 

%%



cd /Volumes/'G-DRIVE mobile USB'/NEW_AOD/AOD_matfiles
load('Dimensions_AOD.mat')
cd /Users/srishtidasarathy/Documents/'Documents - Srishti’s MacBook Pro '/Bowman/SouthernOcean_Causal_Analysis/Variables/AOD_matfiles
save('Dimensions_AOD.mat', 'AOD_Latitude_subset', 'AOD_Longitude_subset', '-v7.3')




%%
% Only select pixels with greater than or equal to X number of observations

pixel_threshold_2007_2018 = Master_AOD_total_pixelcounts_2007_2018 >= 2;
threshold_total_AOD_2007_2018 = Master_AOD_total_2007_2018;
threshold_coarse_AOD_2007_2018 = Master_AOD_coarse_2007_2018;
threshold_fine_AOD_2007_2018 = Master_AOD_fine_2007_2018; 

threshold_total_AOD_2007_2018(~pixel_threshold_2007_2018) = NaN;
threshold_coarse_AOD_2007_2018(~pixel_threshold_2007_2018) = NaN;
threshold_fine_AOD_2007_2018(~pixel_threshold_2007_2018) = NaN;

% Any negative values should also get thrown out (as NAN)

threshold_coarse_AOD_2007_2018(threshold_coarse_AOD_2007_2018<0) = NaN;
threshold_fine_AOD_2007_2018(threshold_fine_AOD_2007_2018<0) = NaN;
threshold_total_AOD_2007_2018(threshold_total_AOD_2007_2018<0) = NaN;


%% Corner Region: 


Latitude_Corner_AOD_logical = AOD_Latitude_subset <= -60 & AOD_Latitude_subset >= -63;
Latitude_Corner_AOD = AOD_Latitude_subset(Latitude_Corner_AOD_logical);

Longitude_Corner_AOD_logical = AOD_Longitude_subset >= -100 & AOD_Longitude_subset <= -80;
Longitude_Corner_AOD = AOD_Longitude_subset(Longitude_Corner_AOD_logical);

% Selecting only Corner region now:
Corner_Region_AOD_total_fullres = threshold_total_AOD_2007_2018(Latitude_Corner_AOD_logical, Longitude_Corner_AOD_logical,  :);
Corner_Region_AOD_coarse_fullres = threshold_coarse_AOD_2007_2018(Latitude_Corner_AOD_logical, Longitude_Corner_AOD_logical,  :);
Corner_Region_AOD_fine_fullres = threshold_fine_AOD_2007_2018(Latitude_Corner_AOD_logical, Longitude_Corner_AOD_logical,  :);



%%

Corner_AOD_total_daily = zeros(1,length(Corner_Region_AOD_total_fullres(1,1,:)));
Corner_AOD_coarse_daily = zeros(1,length(Corner_Region_AOD_coarse_fullres(1,1,:)));
Corner_AOD_fine_daily = zeros(1, length(Corner_Region_AOD_fine_fullres(1,1,:)));

for i = 1: length(Corner_Region_AOD_total_fullres(1,1,:))
    Corner_AOD_total_daily(i) = nanmean(Corner_Region_AOD_total_fullres(:,:,i), [1 2]);
    Corner_AOD_coarse_daily(i) = nanmean(Corner_Region_AOD_coarse_fullres(:,:,i), [1 2]);
    Corner_AOD_fine_daily(i) = nanmean(Corner_Region_AOD_fine_fullres(:,:,i), [1 2]);
end

Corner_AOD_total_daily = Corner_AOD_total_daily';
Corner_AOD_coarse_daily = Corner_AOD_coarse_daily';
Corner_AOD_fine_daily = Corner_AOD_fine_daily';

%% Central Region:

Latitude_Central_AOD_logical = AOD_Latitude_subset <= -66 & AOD_Latitude_subset >= -69;
Latitude_Central_AOD = AOD_Latitude_subset(Latitude_Central_AOD_logical);

Longitude_Central_AOD_logical = AOD_Longitude_subset >= -87 & AOD_Longitude_subset <= -67;
Longitude_Central_AOD = AOD_Longitude_subset(Longitude_Central_AOD_logical);

% Selecting only Central region now:
Central_Region_AOD_total_fullres = threshold_total_AOD_2007_2018(Latitude_Central_AOD_logical,Longitude_Central_AOD_logical, :);
Central_Region_AOD_coarse_fullres = threshold_coarse_AOD_2007_2018(Latitude_Central_AOD_logical,Longitude_Central_AOD_logical, :);
Central_Region_AOD_fine_fullres = threshold_fine_AOD_2007_2018(Latitude_Central_AOD_logical,Longitude_Central_AOD_logical, :);

%%

Central_AOD_total_daily = zeros(1,length(Central_Region_AOD_total_fullres(1,1,:)));
Central_AOD_coarse_daily = zeros(1,length(Central_Region_AOD_coarse_fullres(1,1,:)));
Central_AOD_fine_daily = zeros(1, length(Central_Region_AOD_fine_fullres(1,1,:)));

for i = 1: length(Central_Region_AOD_total_fullres(1,1,:))
    Central_AOD_total_daily(i) = nanmean(Central_Region_AOD_total_fullres(:,:,i), [1 2]);
    Central_AOD_coarse_daily(i) = nanmean(Central_Region_AOD_coarse_fullres(:,:,i), [1 2]);
    Central_AOD_fine_daily(i) = nanmean(Central_Region_AOD_fine_fullres(:,:,i), [1 2]);
end

Central_AOD_total_daily = Central_AOD_total_daily';
Central_AOD_coarse_daily = Central_AOD_coarse_daily';
Central_AOD_fine_daily = Central_AOD_fine_daily';

%% Southernmost Region:

Latitude_Southernmost_AOD_logical = AOD_Latitude_subset <= -70 & AOD_Latitude_subset >= -73;
Latitude_Southernmost_AOD = AOD_Latitude_subset(Latitude_Southernmost_AOD_logical);

Longitude_Southernmost_AOD_logical = AOD_Longitude_subset >= -95 & AOD_Longitude_subset <= -75;
Longitude_Southernmost_AOD = AOD_Longitude_subset(Longitude_Southernmost_AOD_logical);

% Selecting only Southernmost region now:
Southernmost_Region_AOD_total_fullres = threshold_total_AOD_2007_2018(Latitude_Southernmost_AOD_logical, Longitude_Southernmost_AOD_logical,  :);
Southernmost_Region_AOD_coarse_fullres = threshold_coarse_AOD_2007_2018(Latitude_Southernmost_AOD_logical, Longitude_Southernmost_AOD_logical,  :);
Southernmost_Region_AOD_fine_fullres = threshold_fine_AOD_2007_2018(Latitude_Southernmost_AOD_logical, Longitude_Southernmost_AOD_logical,  :);

%%

Southernmost_AOD_total_daily = zeros(1,length(Southernmost_Region_AOD_total_fullres(1,1,:)));
Southernmost_AOD_coarse_daily = zeros(1,length(Southernmost_Region_AOD_coarse_fullres(1,1,:)));
Southernmost_AOD_fine_daily = zeros(1, length(Southernmost_Region_AOD_fine_fullres(1,1,:)));

for i = 1: length(Southernmost_Region_AOD_total_fullres(1,1,:))
    Southernmost_AOD_total_daily(i) = nanmean(Southernmost_Region_AOD_total_fullres(:,:,i), [1 2]);
    Southernmost_AOD_coarse_daily(i) = nanmean(Southernmost_Region_AOD_coarse_fullres(:,:,i), [1 2]);
    Southernmost_AOD_fine_daily(i) = nanmean(Southernmost_Region_AOD_fine_fullres(:,:,i), [1 2]);
end

Southernmost_AOD_total_daily = Southernmost_AOD_total_daily';
Southernmost_AOD_coarse_daily = Southernmost_AOD_coarse_daily';
Southernmost_AOD_fine_daily = Southernmost_AOD_fine_daily';

%% I need to input an NaN where September 25th 2018 is, because this is a missing date. 
% If I do this my days are equal to the rest of my data. 
% I have to insert a NaN at position 4286

t1 = datetime(2007,01,01);
t2 = datetime(2018,12,31);
times_2007_2018 = t1:caldays(1):t2; 
times_2007_2018 = times_2007_2018';
clear t1 t2

Corner_AOD_tt = timetable(times_2007_2018, Corner_AOD_total_daily, Corner_AOD_coarse_daily, Corner_AOD_fine_daily);
Central_AOD_tt = timetable(times_2007_2018, Central_AOD_total_daily, Central_AOD_coarse_daily, Central_AOD_fine_daily);
Southernmost_AOD_tt = timetable(times_2007_2018, Southernmost_AOD_total_daily, Southernmost_AOD_coarse_daily, Southernmost_AOD_fine_daily);

Corner_AOD_TT = retime(Corner_AOD_tt, 'daily', 'fillwithmissing');
Central_AOD_TT = retime(Central_AOD_tt, 'daily', 'fillwithmissing');
Southernmost_AOD_TT = retime(Southernmost_AOD_tt, 'daily', 'fillwithmissing');
%%
 cd /Users/srishtidasarathy/Documents/'Documents - Srishti’s MacBook Pro '/Bowman/SouthernOcean_Causal_Analysis/Variables/AOD_matfiles/
save('AOD_timetables_2pixelthreshold.mat', 'Corner_AOD_TT', 'Central_AOD_TT', 'Southernmost_AOD_TT', '-v7.3')


%% Plotting of seasonal climatologies: This is to make sure I've done the above correctly.
% 
% AOD_Lat = (linspace(AOD_Latitude_subset(1), AOD_Latitude_subset(end), 40)) ; 
% AOD_Lon = (linspace(AOD_Longitude_subset(1), AOD_Longitude_subset(end), 46)); 
% % AOD_Lat = flip(AOD_Lat); % this is for plotting purposes because pcolor flips image on y axis. 
% 
% %% This is just to check how many boxes to divide AOD_Lat and AOD_Lon into
% nAOD_Lat = Latitude_subset(1) : -0.5 : Latitude_subset(end) ; 
% nAOD_Lon = Longitude_subset(1) : 1 : Longitude_subset(end); 
% 
% % nAOD_Lat = flip(nAOD_Lat) ; 

%%

[winter_x, winter_y] = find(times_2007_2018.Month >= 6 & times_2007_2018.Month <= 8);
% Can check if this worked by typing 'times(winter_x)' in command window
times_2007_2018(winter_x)

AOD_total_winter = threshold_total_AOD_2007_2018; 
AOD_total_winter = AOD_total_winter(:,:,winter_x);
AOD_fine_winter = threshold_fine_AOD_2007_2018;
AOD_fine_winter = AOD_fine_winter(:,:,winter_x);
AOD_coarse_winter = threshold_coarse_AOD_2007_2018;
AOD_coarse_winter = AOD_coarse_winter(:,:,winter_x);

Pixel_Counts_winter = Master_AOD_total_pixelcounts_2007_2018(:,:,winter_x);

% For Spring: 
[spring_x, spring_y] = find(times_2007_2018.Month >= 9 & times_2007_2018.Month <= 11);
times_2007_2018(spring_x)
AOD_total_spring = threshold_total_AOD_2007_2018; 
AOD_total_spring = AOD_total_spring(:,:, spring_x); 
AOD_fine_spring = threshold_fine_AOD_2007_2018;
AOD_fine_spring = AOD_fine_spring(:,:,spring_x);
AOD_coarse_spring = threshold_coarse_AOD_2007_2018;
AOD_coarse_spring = AOD_coarse_spring(:,:,spring_x);

Pixel_Counts_spring = Master_AOD_total_pixelcounts_2007_2018(:,:,spring_x);

% For Summer: 

[summer_x, summer_y] = find(times_2007_2018.Month >= 1 & times_2007_2018.Month <=2 | times_2007_2018.Month == 12);

times_2007_2018(summer_x)
AOD_total_summer = threshold_total_AOD_2007_2018; 
AOD_total_summer = AOD_total_summer(:,:, summer_x); 
AOD_fine_summer = threshold_fine_AOD_2007_2018;
AOD_fine_summer = AOD_fine_summer(:,:,summer_x);
AOD_coarse_summer = threshold_coarse_AOD_2007_2018;
AOD_coarse_summer = AOD_coarse_summer(:,:,summer_x);


Pixel_Counts_summer = Master_AOD_total_pixelcounts_2007_2018(:,:,summer_x);

% For Fall: 

[fall_x, fall_y] = find(times_2007_2018.Month >= 3 & times_2007_2018.Month <= 5); 
times_2007_2018(fall_x) 
AOD_total_fall = threshold_total_AOD_2007_2018; 
AOD_total_fall = AOD_total_fall(:,:, fall_x); 
AOD_fine_fall = threshold_fine_AOD_2007_2018;
AOD_fine_fall = AOD_fine_fall(:,:,fall_x);
AOD_coarse_fall = threshold_coarse_AOD_2007_2018;
AOD_coarse_fall = AOD_coarse_fall(:,:,fall_x);

Pixel_Counts_fall = Master_AOD_total_pixelcounts_2007_2018(:,:, fall_x);

% So now for the raw and smoothn climatologies, you can average all of
% these and plot... (for raw) or average all of them and then smoothn on
% the 2D. 

AOD_total_winter_mean = mean(AOD_total_winter,3 ,'omitnan');
AOD_fine_winter_mean = mean(AOD_fine_winter, 3, 'omitnan');
AOD_coarse_winter_mean = mean(AOD_coarse_winter, 3, 'omitnan');
Pixel_Counts_winter_mean = mean(Pixel_Counts_winter, 3, 'omitnan');

AOD_total_spring_mean = mean(AOD_total_spring, 3 , 'omitnan'); 
AOD_fine_spring_mean = mean(AOD_fine_spring, 3, 'omitnan');
AOD_coarse_spring_mean = mean(AOD_coarse_spring, 3, 'omitnan');
Pixel_Counts_spring_mean = mean(Pixel_Counts_spring, 3, 'omitnan');

AOD_total_summer_mean = mean(AOD_total_summer, 3, 'omitnan'); 
AOD_fine_summer_mean = mean(AOD_fine_summer, 3, 'omitnan');
AOD_coarse_summer_mean = mean(AOD_coarse_summer, 3, 'omitnan');
Pixel_Counts_summer_mean = mean(Pixel_Counts_summer, 3, 'omitnan');

AOD_total_fall_mean = mean(AOD_total_fall, 3, 'omitnan'); 
AOD_fine_fall_mean = mean(AOD_fine_fall, 3, 'omitnan');
AOD_coarse_fall_mean = mean(AOD_coarse_fall, 3, 'omitnan');
Pixel_Counts_fall_mean = mean(Pixel_Counts_fall, 3, 'omitnan');


%%
make_it_tight = true;
subplot = @(m,n,p) subtightplot (m, n, p, [0.08 0.08], [0.08 0.08], [0.1 0.1]);
if ~make_it_tight,  clear subplot;  end

fig = figure(1),clf;

subplot(2,2,1)
plot_BSea_figure_subplot(AOD_coarse_winter_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('tempo'), ...
    [0 .15],...
    'Winter'); 


subplot(2,2,2)
plot_BSea_figure_subplot(AOD_coarse_spring_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('tempo'), ...
    [0 .15],...
    'Spring'); 

subplot(2,2,3)
plot_BSea_figure_subplot(AOD_coarse_summer_mean, ...
   AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('tempo'), ...
    [0 .15],...
    'Summer'); 


subplot(2,2,4)
plot_BSea_figure_subplot(AOD_coarse_fall_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('tempo'), ...
    [0 .15],...
    'Fall'); 
    

hp4 = get(subplot(2,2,4),'Position');
h = colorbar('Position', [hp4(1)+hp4(3)+0.02  hp4(2)+0.15  0.02  hp4(2)+hp4(3) * 1.3]);
h.FontWeight = 'bold';
h.FontSize = 15;
hy = ylabel(h, sprintf('Coarse AOD'), 'FontSize', 18);
% hy.FontSize = 18;


%%
cd /Users/srishtidasarathy/Documents/'Documents - Srishti’s MacBook Pro '/Bowman/SouthernOcean_Causal_Analysis/Figures/Possible_Manuscript_Figs
set(gcf,'PaperPositionMode','auto')

print(gcf,'Coarse_AOD_Seasonal_Spatial_Climatology.png','-dpng','-r300');         %  *// 300 dpi





%%
make_it_tight = true;
subplot = @(m,n,p) subtightplot (m, n, p, [0.08 0.08], [0.08 0.08], [0.1 0.1]);
if ~make_it_tight,  clear subplot;  end

fig = figure(2),clf;

subplot(2,2,1)
plot_BSea_figure_subplot(Pixel_Counts_winter_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('dense'), ...
    [0 40],...
    'Winter'); 


subplot(2,2,2)
plot_BSea_figure_subplot(Pixel_Counts_spring_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('dense'), ...
    [0 40],...
    'Spring'); 

subplot(2,2,3)
plot_BSea_figure_subplot(Pixel_Counts_summer_mean, ...
   AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('dense'), ...
    [0 40],...
    'Summer'); 


subplot(2,2,4)
plot_BSea_figure_subplot(Pixel_Counts_fall_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('dense'), ...
    [0 40],...
    'Fall'); 
    

hp4 = get(subplot(2,2,4),'Position');
h = colorbar('Position', [hp4(1)+hp4(3)+0.02  hp4(2)+0.15  0.02  hp4(2)+hp4(3) * 1.3]);
h.FontWeight = 'bold';
h.FontSize = 15;
hy = ylabel(h, sprintf('Pixel Counts of AOD'), 'FontSize', 18);


%%
cd /Users/srishtidasarathy/Documents/'Documents - Srishti’s MacBook Pro '/Bowman/SouthernOcean_Causal_Analysis/Figures/Possible_Manuscript_Figs
set(gcf,'PaperPositionMode','auto')

print(gcf,'PixelCounts_AOD_Seasonal_Spatial_Climatology.png','-dpng','-r300');         %  *// 300 dpi



%% Spatial region CHECK:

Corner_AOD_avg = mean(Corner_Region_AOD_total_fullres,3,'omitnan');
Central_AOD_avg = mean(Central_Region_AOD_total_fullres,3,'omitnan');
Southernmost_AOD_avg = mean(Southernmost_Region_AOD_total_fullres,3,'omitnan');


%%

make_it_tight = true;
subplot = @(m,n,p) subtightplot (m, n, p, [0.08 0.08], [0.08 0.08], [0.1 0.1]);
if ~make_it_tight,  clear subplot;  end

fig = figure(3),clf;

subplot(2,2,1)
plot_BSea_figure_subplot(Corner_AOD_avg, ...
    Longitude_Corner_AOD',...
    Latitude_Corner_AOD',...
    cmocean('algae'), ...
    [0 0.1],...
    'Corner Region Spatial Test'); 


subplot(2,2,2)
plot_BSea_figure_subplot(Central_AOD_avg, ...
    Longitude_Central_AOD',...
    Latitude_Central_AOD',...
    cmocean('algae'), ...
    [0 0.1],...
    'Central Region Spatial Test'); 

subplot(2,2,3)
plot_BSea_figure_subplot(Southernmost_AOD_avg, ...
    Longitude_Southernmost_AOD',...
    Latitude_Southernmost_AOD',...
    cmocean('algae'), ...
    [0 0.1],...
    'Southernmost Region Spatial Test'); 
s
% This is just a dummy to keep the placeholder of subplot 4
subplot(2,2,4)
plot_BSea_figure_subplot(Pixel_Counts_fall_mean, ...
    AOD_Longitude_subset',...
    AOD_Latitude_subset',...
    cmocean('dense'), ...
    [0 40],...
    'Dummy Variable'); 
    

hp4 = get(subplot(2,2,4),'Position');
h = colorbar('Position', [hp4(1)+hp4(3)+0.02  hp4(2)+0.15  0.02  hp4(2)+hp4(3) * 1.3]);
h.FontWeight = 'bold';
h.FontSize = 15;
hy = ylabel(h, sprintf('Total AOD'), 'FontSize', 18);
% hy.FontSize = 18;


%%